### ISSUE TITLE
show_grid: false error

### ISSUE THREAD

**Issue by fmsegre** [dking3876/gantt-ui-component#7]
When show_grid is set to false, reloading the page generates the following error:
ERROR TypeError: Cannot read property 'length' of undefined
    at o._clearLayers (dhtmlxgantt.js:10)...

The first time the page is loaded is OK. This error only happens after that. Can you help?

**Comment by metal-dev-spd** [comment]
Hi,
I had the same error, so i changed the main entry in the package.json (and in bower.json too) file of the **dhtmlxgantt** component from
`"main": "codebase/dhtmlxgantt.js"` 
to
`"main": "codebase/sources/dhtmlxgantt.js"` for use the non minified file source first.

After that, it's easily to find where is the problem(s):
at line 3105:
`for(var i = 0; i < this._taskLayers.length; i++)`
this._taskLayers is undefined, so you have to add before the for command something like that:
`if(this._taskLayers)`.

One you fix that, you will throw another error, the problem is similar, at line 3358
`this._mouseDelegates.destructor();`
this._mouseDelegates is undefined, so you have to add the test before
`if(this._mouseDelegates) {
	this._mouseDelegates.destructor();
}`

I hope I was helpful
regards

**Comment by qq2504021719** [comment]
厉害，我弄了一下午
